### ISSUE TITLE
Autoconvert vagrant key

### ISSUE THREAD

**Issue by techtonik** [nickryand/vagrant-multi-putty#15]
If it is possible for plugin to have its own data then autoconverting a vagrant key to ppk will save a lot of time for many people.

**Comment by stefanschererseal** [comment]
+1. I also thought about it as I now use Vagrant 1.7 and converting the key to PPK for every vagrant box is very awkward.
I'll think about making a PR...

**Comment by StefanScherer** [comment]
At least the plugin already looks for the ppk beside the auto generated key of Vagrant 1.7:

```
Unable to use key file "C:/Users/stefan.scherer/GitHub/plossys/vagrant/ubuntu-intellij/.vagrant/machines/default/virtualbox/private_key.ppk" (unable to open file)
Using username "vagrant".
vagrant@127.0.0.1's password:
```

So only the automatic conversion step is needed.

I found this: http://webdevbyjoss.blogspot.de/2012/04/convert-openssh-keys-to-putty-on-linux.html
Tried it manually on Windows with

```
λ puttygen  "C:/Users/stefan.scherer/GitHub/plossys/vagrant/ubuntu-intellij/.vagrant/machines/default/virtualbox/private_key" -o  "C:/Users
/stefan.scherer/GitHub/plossys/vagrant/ubuntu-intellij/.vagrant/machines/default/virtualbox/private_key.ppk"
```

but there is a popup window:
* *PuTTYgen Notice* 
* Successfully imported foreign key (OpenSSH SSH-2 private key). To use this key with PuTTY, you need to use the "Save private key" command to save it in PuTTY's own format.

It seems that puttygen.exe does not handle these command line options. Any ideas?

**Comment by StefanScherer** [comment]
This doesn't sound good:
* http://stackoverflow.com/questions/16704089/putty-key-generator-command-line-interface
* http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/puttygen-batch.html

So puttygen on Unix is not puttygen on Windows due to the GUI behaviour of C programs on Windows.This is a bit tricky, but solveable AFAIK. But then a PR or whatever is needed for the PuTTY gen project.

Another idea is to convert the SSH key to PPK natively with Ruby. We don't need everything of puttygen, just this conversion step.

Perhaps this code might help as a starting point: http://www.example-code.com/ruby/ssh_ppk_to_pem.asp

**Comment by nickryand** [comment]
I am totally open to this. I'll do some research when I can. I am open to a PR for this.

**Comment by StefanScherer** [comment]
I had a closer look at the Ruby gem chilkat. But rubygems.org is right, there is only a Mac and Linux version of it, but none for Windows. The platform we have the need for PuTTY conversion most.

I even checked it on a Windows machine with following command:

```cmd
C:\Users\vagrant>vagrant plugin install chilkat
Installing the 'chilkat' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Could not find gem 'chilkat (>= 0) x86-mingw32' in the gems available on this machine.
```

So it seems that it is nearly impossible to find a solution for Windows that is easier than helping the PuTTY team eg. reading id_rsa natively (as there is a conversion routine linked into puttygen.exe) or give the puttygen.exe the same command line option as for the Linux version.

For Mac and Linux there both is the chilkat gem, but also the command line tool puttygen.

**Comment by fkrull** [comment]
So, I looked into that a bit and managed to get a rough solution working:

1) compile the Unix `puttygen` for Windows (as `puttygen-cmd`)
2) modify `vagrant-multi-putty` to use it
3) ?
4) profit

See https://bitbucket.org/fk/putty; there's a prebuilt version of `puttygen-cmd` in the Downloads section (or you can build it yourself, the "puttygen-cmd-windows" branch). I've also modified `vagrant-multi-putty` to use that program (if it's in your PATH) to convert OpenSSH keys if necessary (https://github.com/fkrull/vagrant-multi-putty/tree/convert-key). So, with that branch, you can just drop a `puttygen-cmd` into your PATH and `vagrant putty` should start autoconverting OpenSSH keys in most common situations.

I guess I'll have to present this to PuTTY upstream and see how that turns out before opening a pull request; in case the binary name has to change for example. Still, if you need this feature right now, you can have it.

**Comment by StefanScherer** [comment]
@fkrull Great approach! So if it is possible to build the command line tool on Windows to do the conversion, there should be also a way to integrate that into the puttygen.exe. I'll have a look at your branch.

**Comment by mightydok** [comment]
@fkrull thnx, works like a charm. Can you create pull request for this feature?

**Comment by fkrull** [comment]
Sorry, that took longer than I planned, but I've now hit up the PuTTY guys to see if we can get this change upstreamed. I'll create a pull request when that is cleared up.

**Comment by nickryand** [comment]
Thanks for the follow up on this.

**Comment by fkrull** [comment]
I can't really spend any more time chasing after PuTTY, so I opened a pull request now: https://github.com/nickryand/vagrant-multi-putty/pull/19.

**Comment by philr** [comment]
I've created a library called [PuTTY::Key](https://github.com/philr/putty-key) that can handle the conversion of private keys to PuTTY's .ppk format. This requires only the Ruby OpenSSL standard library - it has no dependency on PuTTY or any of its related tools.

As an alternative to pull request #19, I've opened pull request #20 to handle automatic conversion using PuTTY::Key. This avoids the requirement for a new `puttygen-cmd` command line executable.

**Comment by nickryand** [comment]
This has been pushed! Thanks for this!!

https://rubygems.org/gems/vagrant-multi-putty/versions/1.5.0

**Comment by stefanschererseal** [comment]
Works out of the box. Thank you very much!

**Comment by mightydok** [comment]
Thx, it works!

**Comment by bradisbell** [comment]
This is awesome!  Vagrant is useful again!  Thanks all!!!
